<?php

/**
 * @file
 * Populate DynamicExample content.
 */

/**
 * Implements hook_migrate_api().
 */
function dynamic_example_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'DynamicExampleCompaniesMigrate',
    'DynamicExampleEventsMigrate',
    // Users.
    'DynamicExampleUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
